name: sofie_ui
description: Social Fitness Elevated.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  artemis: ^7.2.6-beta
  async: ^2.8.1
  auto_route: 3.1.2 # https://github.com/Milad-Akarie/auto_route_library/issues/853
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  custom_pop_up_menu: ^1.2.0
  email_validator: ^2.0.1
  equatable: ^2.0.0
  file_picker: ^4.2.2
  firebase_auth: ^3.1.3
  firebase_core: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  flutter_vibrate: ^1.3.0
  get_it: ^7.1.4
  google_fonts: ^2.1.0
  gql: ^0.13.0
  gql_dedupe_link: ^2.0.0
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2
  implicitly_animated_reorderable_list: ^0.4.1
  infinite_scroll_pagination: ^3.0.1+1
  intl: ^0.17.0
  json_annotation: ^4.1.0
  just_audio: ^0.9.17
  logger: ^1.1.0
  meta: ^1.7.0
  modal_bottom_sheet: ^2.0.0
  native_device_orientation: ^1.0.0
  normalize: ^0.5.5
  package_info_plus: ^1.3.0
  path_drawing: ^0.5.1+1
  path_provider: ^2.0.5
  percent_indicator: ^3.4.0
  photo_view: ^0.13.0
  popover: ^0.2.6+3
  provider: ^6.0.1
  record: ^3.0.0
  rxdart: ^0.27.2
  scroll_to_index: ^2.1.0
  share_plus: ^3.0.2
  shimmer: ^2.0.0
  simple_animations: ^4.0.1
  sliding_up_panel: ^2.0.0+1
  stop_watch_timer: ^1.3.0 # Controller only - no UI. Provides streams and sinks.
  stream_chat_flutter: ^3.2.0
  stream_feed: ^0.4.0
  substring_highlight: ^1.0.33
  supercharged: ^2.1.1
  syncfusion_flutter_charts: ^19.3.45+1
  syncfusion_flutter_gauges: ^19.3.45
  syncfusion_flutter_pdfviewer: ^19.3.57-beta
  table_calendar: ^3.0.0
  timeline_tile: ^2.0.0
  uni_links: ^0.5.1
  uploadcare_flutter: ^1.0.2
  uuid: ^3.0.5
  video_player: ^2.2.5
  wakelock: ^0.5.6
  xml: ^5.3.0

dependency_overrides:
  provider: ^6.0.1
  gql_exec: 0.3.0

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_app_name: ^0.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
  json_serializable: ^6.0.1

flutter_app_name:
  name: "Sofie"

flutter_icons:
  # Android
  android: true
  image_path_android: "assets/logos/sofie_launcher_icon_android.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logos/sofie_launcher_icon_android.png"
  # ios
  ios: true
  image_path_ios: "assets/logos/sofie_launcher_icon_ios.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: "assets/logos/sofie_splash_image.png"
  info_plist_files:
   - 'ios/Runner/Info-Debug.plist'
   - 'ios/Runner/Info-Release.plist'

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/audio/do_workout/
    - assets/body_areas/
    - assets/body_areas/front/
    - assets/body_areas/front/selection/
    - assets/body_areas/back/
    - assets/body_areas/back/selection/
    - assets/equipment_icons/
    - assets/flags/png/
    - assets/graphics/
    - assets/category_icons/
    - assets/logos/
    - assets/other_app_icons/
    - assets/placeholder_images/
    - assets/workout_filters_icons/