name: sofie_ui
description: Social Fitness Elevated.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  animations: ^2.0.3
  another_flushbar: ^1.10.29
  artemis: ^7.7.0-beta
  async: ^2.8.2
  audio_session: ^0.1.6+1
  auto_route: ^4.0.1
  cached_network_image: ^3.2.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  custom_pop_up_menu: ^1.2.3+2
  dio: ^4.0.6 # Need this for StreamChat media upload Cancel token.
  dotted_line: ^3.1.0
  email_validator: ^2.0.1
  equatable: ^2.0.3
  feedback: ^2.5.0
  file_picker: ^4.6.0
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.18
  flutter:
    sdk: flutter
  flutter_emoji: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^1.3.0
  flutter_svg: ^1.1.0
  flutter_vibrate: ^1.3.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  gql: ^0.13.1
  gql_dedupe_link: ^2.0.3-alpha+1645425888429
  gql_exec: ^0.4.1-alpha+1645425888344
  gql_http_link: ^0.4.3-alpha+1645425888380
  gql_link: ^0.4.3-alpha+1645425888352
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  implicitly_animated_reorderable_list: ^0.4.2
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  just_audio: ^0.9.21
  logger: ^1.1.0
  lottie: ^1.3.0
  loading_animation_widget: ^1.2.0+1
  meta: ^1.7.0
  native_device_orientation: ^1.1.2
  # normalize: ^0.6.0+1
  package_info_plus: ^1.4.2
  path_drawing: ^1.0.0
  path_provider: ^2.0.10
  percent_indicator: ^4.2.2
  photo_view: ^0.13.0
  popover: ^0.2.6+3
  provider: ^6.0.3
  record: ^4.1.1
  rxdart: ^0.27.3
  scroll_to_index: ^3.0.1
  sentry_flutter: ^6.5.1
  share_plus: ^4.0.4
  shimmer: ^2.0.0
  simple_animations: ^4.0.2
  sliding_up_panel: ^2.0.0+1
  stop_watch_timer: ^1.4.0 # Controller only - no UI. Provides streams and sinks.
  stream_chat_flutter: ^4.2.0
  stream_feed: ^0.5.2
  substring_highlight: ^1.0.33
  supercharged: ^2.1.1
  syncfusion_flutter_charts: ^20.1.56
  syncfusion_flutter_gauges: ^20.1.56
  syncfusion_flutter_pdfviewer: ^20.1.56-beta
  table_calendar: ^3.0.5
  timeline_tile: ^2.0.0
  uni_links: ^0.5.1
  uploadcare_flutter: ^3.0.1
  url_launcher: ^6.1.2
  uuid: ^3.0.6
  video_player: ^2.4.2
  video_thumbnail: ^0.5.0
  wakelock: ^0.6.1+2
  xml: ^6.1.0

# dependency_overrides:

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  json_serializable: ^6.2.0

flutter_icons:
  # Android
  android: true
  image_path_android: "assets/logos/android_launcher_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logos/android_launcher_icon.png"
  # ios
  ios: true
  image_path_ios: "assets/logos/ios_launcher_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: "assets/logos/android_launcher_icon.png"
  info_plist_files:
   - 'ios/Runner/Info-Debug.plist'
   - 'ios/Runner/Info-Release.plist'

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/audio/do_workout/
    - assets/body_areas/
    - assets/body_areas/front/
    - assets/body_areas/front/selection/
    - assets/body_areas/back/
    - assets/body_areas/back/selection/
    - assets/category_icons/
    - assets/equipment_icons/
    - assets/flags/png/
    - assets/graphics/
    - assets/landing/
    - assets/logos/
    - assets/lottie/
    - assets/other_app_icons/
    - assets/placeholder_images/
    - assets/workout_filters_icons/
    - assets/workout_icons/
    
  fonts:
  - family: Bauhaus
    fonts:
    - asset: fonts/Bauhaus93.ttf
  - family: MyCustomIcons
    fonts:
    - asset: fonts/MyCustomIcons.ttf
  - family: WorkoutType
    fonts:
    - asset: fonts/WorkoutType.ttf
